### ISSUE TITLE
Dois je traduire quand c'est les commentaires de fichiers de conf ?

### ISSUE THREAD

**Issue by Hettomei** [railsfrance/docrails#11]
Salut à tous, pas facile de se motiver seul dans son coin... (surtout que j'ai lu un article comme quoi traduire ce perdais et que pour apprendre à coder, fallait apprendre l'anglais....)

Bref, question, j'ai ça :

``` ruby
# Your secret key for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
YourApp::Application.config.secret_key_base = '49d3f3de9ed86c74b94ad6bd0...'
```
- Est ce que je traduis chaque commentaire ?
- Est ce que je traduis "YourApp" par "VotreApp" ?

merci

**Comment by Hettomei** [comment]
J'ai oublié de préciser, avant il est écris :

<< Rails met en place (pour le stockage par cookie) une clé secrète utilisée pour la signature des données de session. Ceci peut être modifié dans `config/initializers/secret_token.rb` : >>
suivis du code que j'ai noté plus haut.

**Comment by simonc** [comment]
Salut @Hettomei,

De mon point de vue pas besoin de le traduire, au final ça montre le code du fichier généré par Rails,
du coup le commentaire est en anglais. Vu que le contexte est expliqué juste au dessus ça ne me semble
pas nécessaire.

Je pense que les commentaires à traduire sont ceux qui accompagnent les exemples d'utilisation genre
dans un modèle ou autre.

J'espère que ça répond à ta question pour la suite.

C'est vrai que ces derniers temps c'est un peu difficile de s'occuper de la traduction. Chacun a ses projets et le taff du coup ça passe un peu au second plan. C'est pas pour tout de suite mais à la fin de l'année je serai beaucoup plus dispo pour ce genre de choses ;)

**Comment by Hettomei** [comment]
Ça répond, merci.

Ouaip, le temps la motiv' tout ça tout ça, c'est dur.
