### ISSUE TITLE
Le dictionnaire

### ISSUE THREAD

**Issue by simonc** [railsfrance/docrails#2]
Je viens d'ajouter quelques traductions au dictionnaire.
J'ai laissé pas mal d'entrées vides parce que je pense que leur traduction se discute. De plus, certains termes devraient peut-être rester en anglais.

Qu'est-ce que vous en pensez ?

Sur quoi se base cette liste d'ailleurs ?

**Comment by gdurelle** [comment]
Je suis assez d'accord certains termes doivent rester en anglais. On en avait discuté longuement sur le googlegroupe d'ailleurs :)
Par contre comment décider ? Chaque mots sera sujet à débat donc bon... garder les mots techniques et mots clefs du language et framework en anglais (genre before filter reste before filter), et on traduit le reste.
Mais faudrait un truc de vote à la doodle ou je sais pas quoi ?

Pour ce que tu as déjà rempli je suis d'accord sur tout. 
Je rajouterai credentials = identifiants. Pour les autres vides, beaucoup en anglais sont bien.

**Comment by sush** [comment]
Pour le wiki j'ai un peu copié le [wiki](https://github.com/apohllo/docrails/wiki) de la team de traducteurs Polonais.
Ils ont l'air de s'en sortir pas mal.

Apres n'ayant aucune expérience en matière de traduction, si tu as un workflow particulier, fais toi plaisir :)
J'ai créé le wiki en 5 minutes et sa structure peut surement être revue.

**Comment by simonc** [comment]
Ok, cool :)
J'ai failli mettre identifiants mais je me suis dit que ce serait peut-être à discuter.

Pour la discussion autour des mots j'ai pas vu passer oO, c'est sur RailsFR ?

**Comment by gdurelle** [comment]
Ici : http://groups.google.com/group/railsfrance/browse_thread/thread/6486151ab4ae5276 :)

**Comment by simonc** [comment]
@Sush:

Pas de workflow particulier, pour asciicasts ça marche par numéro d'épisode. En gros tu as toute la liste et tu mets 'in progress (username)' en face de ce que tu es en train de traduire et 'translated' une fois le travail terminé, pushé, pullé.

C'est un 'workflow' comme un autre mais bon au pire on verra sur le temps ce qui marche le mieux :)

@gdurelle: Merci !
