### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by simonc** [railsfrance/docrails#4]
Vous le traduiriez comment ? Pour le moment j'ai laissé _placeholder_ parce que je ne sais pas si c'est vraiment à traduire ou pas.

**Comment by pi3r** [comment]
Très bonne question... Je vois pas de traduction potable :confounded:

**Comment by simonc** [comment]
Pareil. En fait je pensais le laisser tel quel.

**Comment by pi3r** [comment]
Ouep, je pense que c'est mieux.

**Comment by simonc** [comment]
Ok je vais mettre le wiki à jour :)

**Comment by rbellec** [comment]
Pardon d'intervenir tard,
je m'étais posé la question et j'avais pensé à "marqueur de position" avec "(NDT: placeholder)" entre parenthèses à côté.

**Comment by simonc** [comment]
Comme je le propose dans l'issue #5, je pense que la marche à suivre pour ce genre de terme serait de conserver la terminologie anglaise tout en ajoutant, après la première occurrence du mot la traduction entre parenthèses. D'ailleurs, mettre le mot original en italique permet de souligner cette particularité.

> ... la valeur du _placeholder_ (marqueur de position) ...
