### ISSUE TITLE
namespace

### ISSUE THREAD

**Issue by simonc** [railsfrance/docrails#5]
Pour celui-là, je serais d'avis de le laisser mais en précisant, après la première occurrence de la page, `(espace de nom)`.

On s'adresse tout de même à des semi-débutants qui ont déjà une petite expérience en développement.

**Comment by simonc** [comment]
_espace de nom_ ou _espace de nommage_ d'ailleurs ?

**Comment by pi3r** [comment]
Tu peux toujours renvoyer vers la page wikipedia :D

**Comment by simonc** [comment]
J'y ai pensé mais je me suis dit que ça sortait un peu du scope de la traduction.
