### ISSUE TITLE
traduction : query string parameters.

### ISSUE THREAD

**Issue by Hettomei** [railsfrance/docrails#8]
Bien le bonjour,

Vous auriez une idée pour traduire "query string parameters."
dans la phrase :
<< parameters that are sent as part of the URL, called query string parameters. >>
ma version:
les parametres qui font partis de l'URL sont appelés parametres de requete.

Mais je ne suis pas fan de ma version.

**Comment by simonc** [comment]
Pour moi, _query string_ a un sens assez fort techniquement et devrait être conservé en anglais.
Je suis pour que les termes anglais soient mis entre `_` :

> les parametres qui font partis de l'URL, appelés parametres de _query string_.

**Comment by Hettomei** [comment]
La simplicité :) j'aime ça.
Je vais faire ça, si ça ne plait pas au moment de la relecture je changerais. Merci.
